Command line example 1::

        --include=local.conf
        --softvol=yes
        --ass=yes
        --embeddedfonts=yes
        --vf-add=screenshot
        --vo=vdpau=[ deint=-4 pullup ]
        --vc=[ item=ffmpeg12vdpau item=ffwmv3vdpau item=ffc1vdpau item=ffh264vdpau SUPER ]
        --vc-pre=ffh264vdpau
        --vc-pre=[ item=ffc1vdpau ]
        --vc-pre=ffwmv3vdpau
        --vc-pre=ffmpeg12vdpau
        --vo=xv
        --lavdopts=[ threads=4 ]
        --ao=alsa
        --include=/usr/share/doc/mplayer/examples/encoding-example-profiles.conf
        --profile=enc-to-iphone
        --vf-add=ass
        --ass-force-style="Fontname=sans"
        --ovcopts-add=[ tune=animation threads=4 ]

Config example 1::

        include = local.conf
        # softvol = yes
        # softvol-max = 1200
        ass = yes
        embeddedfonts = yes
        vf-add = screenshot
        #vo = vdpau = [
        #       deint = -4
        #       pullup
        #]
        #vc = [
        #       item = ffmpeg12vdpau
        #       item = ffwmv3vdpau
        #       item = ffc1vdpau
        #       item = ffh264vdpau
        #       SUPER
        #]
        # latter doing the same as
        #vc-pre = ffh264vdpau
        #vc-pre = ffc1vdpau
        #vc-pre = ffwmv3vdpau
        #vc-pre = ffmpeg12vdpau
        vo = xv
        lavdopts = [
                threads = 4
        ]
        ao = alsa
        include = /usr/share/doc/mplayer/examples/encoding-example-profiles.conf
        [enc]
        profile = enc-to-iphone
        vf-add = ass
        ass-force-style = "Fontname=sans"
        ovcopts-add = [
                tune = animation
                threads = 4
        ]
        # NOTE:
        # general shortcut for list options:
        #
        # listoption = FOO,BAR
        # means
        # listoption = [
        #       item = FOO
        #       item = BAR
        # ]
        #
        # listoption-add = [
        #       XYZZY
        # ]
        # means
        # listoption = [
        #       SUPER
        #       XYZZY
        # ]
        #
        # listoption-pre = [
        #       XYZZY
        # ]
        # means
        # listoption = [
        #       XYZZY
        #       SUPER
        # ]

Command line example 2 (list starters are their own argument; an ambiguity ensues and is resolved by "if [ can be a list starter, it is and starts a list in the innermost scope possible"); we basically replaced =[ by space and [::

        --include=local.conf
        --softvol=yes
        --ass=yes
        --embeddedfonts=yes
        --vf-add=screenshot
        --vo=vdpau [ deint=-4 pullup ]
        --vc [ item=ffmpeg12vdpau item=ffwmv3vdpau item=ffc1vdpau item=ffh264vdpau SUPER ]
        --vc-pre=ffh264vdpau
        --vc-pre [ item=ffc1vdpau ]
        --vc-pre ffwmv3vdpau
        --vc-pre ffmpeg12vdpau
        --vo=xv
        --lavdopts [ threads=4 ]
        --ao=alsa
        --include=/usr/share/doc/mplayer/examples/encoding-example-profiles.conf
        --profile=enc-to-iphone
        --vf-add=ass
        --ass-force-style="Fontname=sans"
        --ovcopts-add [ tune=animation threads=4 ]

Config example 2 (basically = [ replaced by mere [)::

        include = local.conf
        # softvol = yes
        # softvol-max = 1200
        ass = yes
        embeddedfonts = yes
        vf-add = screenshot
        #vo = vdpau [
        #       deint = -4
        #       pullup
        #]
        #vc [
        #       item = ffmpeg12vdpau
        #       item = ffwmv3vdpau
        #       item = ffc1vdpau
        #       item = ffh264vdpau
        #       SUPER
        #]
        # latter doing the same as
        #vc-pre = ffh264vdpau
        #vc-pre = ffc1vdpau
        #vc-pre = ffwmv3vdpau
        #vc-pre = ffmpeg12vdpau
        vo = xv
        lavdopts [
                threads = 4
        ]
        ao = alsa
        include = /usr/share/doc/mplayer/examples/encoding-example-profiles.conf
        [enc]
        profile = enc-to-iphone
        vf-add = ass
        ass-force-style = "Fontname=sans"
        ovcopts-add [
                tune = animation
                threads = 4
        ]
        # NOTE:
        # general shortcut for list options:
        #
        # listoption = FOO,BAR
        # means
        # listoption [
        #       item = FOO
        #       item = BAR
        # ]
        #
        # listoption-add [
        #       XYZZY
        # ]
        # means
        # listoption [
        #       SUPER
        #       XYZZY
        # ]
        #
        # listoption-pre [
        #       XYZZY
        # ]
        # means
        # listoption [
        #       XYZZY
        #       SUPER
        # ]