Will remove: vf_1bpp, vf_2xsai, vf_blackframe, vf_bmovl, vf_boxblur, vf_cropdetect, vf_decimate, vf_detc, vf_dint, vf_dvbscale, vf_eq2, vf_eq, vf_field, vf_fil, vf_filmdint, vf_fixpts, vf_framestep, vf_fspp, vf_geq, vf_halfpack, vf_harddup, vf_hue, vf_il, vf_ivtc, vf_kerndeint, vf_lavc, vf_lavcdeint, vf_mcdeint, vf_palette, vf_perpective, vf_pp7, vf_qp, vf_rectangle, vf_remove_logo, vf_rgbtest, vf_sab, vf_smartblur, vf_softskip, vf_spp, vf_telecine, vf_test, vf_tile, vf_uspp, vf_yuvcsp, vf_yvu9, vf_denoise3d, vf_ow, vf_phase, vf_tfields, vf_tinterlace

Reasons etc. see below.

libaf/af_bs2b.c
  Sounds useful. Kind of the 2ch variant of hrtf...  now, if we had a filter that is hrtf for multichannel input, and bs2b for 2ch...

  KEEP: divVerent

libaf/af_center.c
  Sounds useful.

  KEEP: divVerent
  REMOVE: lachs0r – That kind of mixing can be done with af_pan. In fact, such mixing should be (and usually is) done by the audio driver.

libaf/af_channels.c
  Somewhat useful for multichannel audio with messed-up channel mappings (such as FLAC).

  KEEP: divVerent, lachs0r

libaf/af_delay.c
  KEEP: divVerent
  ABSTAIN: lachs0r – Useful, but maybe audio drivers can do that?

libaf/af_dummy.c
  REMOVE: divVerent

libaf/af_equalizer.c
  KEEP: divVerent

libaf/af_export.c
  Does anyone use this?

  REMOVE: divVerent

libaf/af_extrastereo.c
  KEEP: divVerent
  REMOVE: lachs0r – Doesn’t sound good at all. Also, equivalent filters exist at least as LADSPA plugins and in most newer Windows audio drivers.

libaf/af_format.c
  KEEP: divVerent

libaf/af_hrtf.c
  KEEP: divVerent

libaf/af_karaoke.c
  Better done via LADSPA, or -af pan
  Most Windows audio drivers can do that too.

  REMOVE: divVerent, lachs0r

libaf/af_ladspa.c
  KEEP: divVerent

libaf/af_lavcac3enc.c
  Apparently useful for SPDIF guys.

  KEEP: divVerent
  ABSTAIN: lachs0r – Need to check if it actually works. Also, at least on Linux, there’s an ALSA plugin to do that.

libaf/af_lavcresample.c
  Do we need two resamplers? Is this one better, or is af_resample? Probably we only want to keep whichever is the better one?
  I don't know, but lavcresample is the default resampler.

  ABSTAIN: divVerent
  KEEP: wm4, lachs0r

libaf/af_pan.c
  KEEP: divVerent

libaf/af_resample.c
  KEEP: divVerent
  REMOVE: lachs0r – Just let libav take care of it.

libaf/af_scaletempo.c
  KEEP: divVerent

libaf/af_sinesuppress.c
  KEEP: divVerent

libaf/af_sub.c
  KEEP: divVerent
  REMOVE: lachs0r – See af_center. ALSA doesn’t do lowpass filtering by default, but there are very good LADSPA plugins for that. Some drivers do it on Windows. In a lot of cases, the speaker/amplifier hardware does it anyway.

libaf/af_surround.c
  KEEP: divVerent

libaf/af_sweep.c
  Use LADSPA if you really want this.

  REMOVE: divVerent, lachs0r

libaf/af_volnorm.c
  Generally a very good filter, but I just can't get it to work. Maybe needs fixing bugs.

  ABSTAIN: divVerent

  lachs0r: This isn’t proper normalization but more like drc with a huge delay. Actual, decent volume normalization is done by tools like normalize(1).

libaf/af_volume.c
  KEEP: divVerent

libmpcodecs/vf_1bpp.c
  Isn't this scale's job?

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_2xsai.c
  Perhaps move to vf_dlopen instead? Sure shouldn't be in mplayer (it's a filter for palette images like old video game footage, but all the nice properties 2xSaI depends on break when using lossy codecs anyway).

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_ass.c
  KEEP: divVerent

libmpcodecs/vf_blackframe.c
  Not really useful on its own, messy output... probably should be coded in vf_dlopen instead.

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_bmovl.c
  No good, only evil can be done with this. Also, weirdly complex.

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_boxblur.c
  We only need one blur, and this is not the one.

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_crop.c
  KEEP: divVerent

libmpcodecs/vf_cropdetect.c
  Probably should be merged with vf_rectangle and moved to vf_dlopen.

  REMOVE: divVerent

libmpcodecs/vf_decimate.c
  Not needed/useful with modern video codecs. Also, was an encoding-only filter. Well, maybe port it to vf_dlopen if anyone really needs it.

  REMOVE: divVerent

libmpcodecs/vf_delogo.c
  KEEP: divVerent, lachs0r
  REMOVE: wm4 (does this thing really work?)

  lachs0r: There’s a less obvious use case for this filter that I’ve suggested to someone in #mplayer2 once. The guy had some 16:9 plasma TV which would exhibit nasty burn-in on pillarboxed 4:3 footage. This filter can be used to mask the black bars. Works surprisingly well.

libmpcodecs/vf_denoise3d.c
  hqdn3d is supposedly higher quality, and not much slower. So this one has no point.

  REMOVE: divVerent

libmpcodecs/vf_detc.c
  One of the worse deteleciners.

  REMOVE: divVerent

libmpcodecs/vf_dint.c
  What is THIS thing good for?

  Apparently, it is for generating abort()s::

    mplayer: libmpcodecs/vf.c:288: vf_get_image: Assertion `vf->w > 0' failed.
    
    Program received signal SIGABRT, Aborted.
    0x00007ffff0daafa5 in raise () from /lib/libc.so.6
    (gdb) bt
    #0  0x00007ffff0daafa5 in raise () from /lib/libc.so.6
    #1  0x00007ffff0dac428 in abort () from /lib/libc.so.6
    #2  0x00007ffff0da4002 in __assert_fail_base () from /lib/libc.so.6
    #3  0x00007ffff0da40b2 in __assert_fail () from /lib/libc.so.6
    #4  0x00000000004ad660 in vf_get_image (vf=0xd560f0, outfmt=842094169, mp_imgtype=2, mp_imgflag=0, w=720,     h=480) at libmpcodecs/vf.c:288
    #5  0x00000000004b787c in config (vf=0xb9b9b0, width=720, height=480, d_width=853, d_height=480, flags=0,     outfmt=842094169)
        at libmpcodecs/vf_dint.c:51
    #6  0x00000000004aeada in vf_config_wrapper (vf=0xb9b9b0, width=720, height=480, d_width=853, d_height=480,     flags=0, outfmt=842094169)
        at libmpcodecs/vf.c:690
    #7  0x00000000004aa5fc in mpcodecs_config_vo2 (sh=0x88d3a0, w=720, h=480, outfmts=0x7fffffffe1d0,     preferred_outfmt=842094169)
        at libmpcodecs/vd.c:277
    #8  0x00000000004abb11 in init_vo (sh=0x88d3a0, pix_fmt=PIX_FMT_YUV420P) at libmpcodecs/vd_ffmpeg.c:447
    #9  0x00000000004ac957 in decode (sh=0x88d3a0, packet=0xc159d0, data=0xc3e9e0, len=28100, flags=0,     reordered_pts=0x7fffffffe398)
        at libmpcodecs/vd_ffmpeg.c:733
    #10 0x00000000004a602e in decode_video (sh_video=0x88d3a0, packet=0xc159d0, start=0xc3e9e0 "",     in_size=28100, drop_frame=0, pts=1)
        at libmpcodecs/dec_video.c:417
    #11 0x0000000000423322 in update_video (mpctx=0x8175a0) at mplayer.c:2546
    #12 0x0000000000425647 in run_playloop (mpctx=0x8175a0) at mplayer.c:3163
    #13 0x0000000000428e35 in play_current_file (mpctx=0x8175a0) at mplayer.c:4097
    #14 0x000000000042901e in play_files (mpctx=0x8175a0) at mplayer.c:4146
    #15 0x0000000000429bcd in main (argc=5, argv=0x7fffffffe7b0) at mplayer.c:4407

  REMOVE: divVerent

libmpcodecs/vf_divtc.c
  Not sure, never tested it, it sounds like a nice filter to fix a mess others have created.

  ABSTAIN: divVerent
  
  Useful with hard-telecined videos that were field-matched but not decimated.

  KEEP: nodame

libmpcodecs/vf_dlopen.c
  KEEP: divVerent

libmpcodecs/vf_down3dright.c
  Sounds useful enough. Could be ported to vf_dlopen, though.
  What's the difference to vf_stereo3d?

  KEEP: divVerent

libmpcodecs/vf_dsize.c
  KEEP: divVerent

libmpcodecs/vf_dvbscale.c
  Sounds useful for encoding sometimes, even though we no longer have DVB support. Also, just use -vf scale parameters...

  REMOVE: divVerent, lachs0r

  lachs0r: You don’t do aspect scaling while encoding from DVB. You set the AR info in the container/video stream.

libmpcodecs/vf_eq2.c
  vf_scale lacks gamma, is otherwise equivalent to this one (note: use --brightness, --contrast, --saturation options to control vf_scale). Gamma can be done trivially using vf_lua.

  REMOVE: divVerent

libmpcodecs/vf_eq.c
  Redundant with vf_scale which has a superset of these controls (it also has saturation).

  REMOVE: divVerent

libmpcodecs/vf_expand.c
  KEEP: divVerent

libmpcodecs/vf_field.c
  If anyone ever needs it: vf_dlopen.

  REMOVE: divVerent

libmpcodecs/vf_fil.c
  WTF. See manpage.

  REMOVE: divVerent

libmpcodecs/vf_filmdint.c
  Kind of redundant with pullup, and slightly worse.

  REMOVE: divVerent

libmpcodecs/vf_fixpts.c
  Never useful.

  REMOVE: divVerent

libmpcodecs/vf_flip.c
  KEEP (but maybe make the name clearer): divVerent

libmpcodecs/vf_format.c
  KEEP: divVerent

libmpcodecs/vf_framestep.c
  REMOVE: divVerent

libmpcodecs/vf_fspp.c
  One of the many WTF filters.

  REMOVE: divVerent

libmpcodecs/vf_geq.c
  Obsolete due to vf_lua.

  REMOVE: divVerent

libmpcodecs/vf_gradfun.c
  De-banding. Has a bad name though. Fix name please!
  The name is just the algorithm's name. Everyone calls it like this.

  KEEP (but rename): divVerent
  ABSTAIN: lachs0r – Better/tweaked implementations of this filter as well as more effective alternatives exist  as AviSynth filters and should replace this one once Someone™ ports one of them. Also, some of the inline assembly is broken (should be yasm-ified and put into separate files anyway).

libmpcodecs/vf_halfpack.c
  Can't scale do this?

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_harddup.c
  Does as much as the goggles: nothing.

  REMOVE: divVerent, lachs0r

libmpcodecs/vf_hqdn3d.c
  KEEP: divVerent

libmpcodecs/vf_hue.c
  REMOVE (and merge with eq2): divVerent

libmpcodecs/vf_il.c
  Do this with vf_lua instead. Can clearly be done in an one-liner.

  REMOVE: divVerent

libmpcodecs/vf_ilpack.c
  This sounds kind of more useful.
  It "sounds" useful? Is it useful or not? Would you actually miss it?

  KEEP: divVerent
  REMOVE: wm4

libmpcodecs/vf_ivtc.c
  Another of the worse deteleciners.

  REMOVE: divVerent

libmpcodecs/vf_kerndeint.c
  A bad deinterlacer.

  REMOVE: divVerent

libmpcodecs/vf_lavc.c
  For DVB output devices. We removed that support.

  REMOVE: divVerent

libmpcodecs/vf_lavcdeint.c
  A bad deinterlacer.

  REMOVE: divVerent

libmpcodecs/vf_mcdeint.c
  A broken deinterlacer that uses lavc internals.

  REMOVE: divVerent

libmpcodecs/vf_mirror.c
  KEEP (but maybe make the name clearer): divVerent

libmpcodecs/vf_noformat.c
  KEEP: divVerent

libmpcodecs/vf_noise.c
  KEEP: divVerent

libmpcodecs/vf_ow.c
  It is very slow, like, 1 frame per 2 seconds. I highly doubt it has enough quality benefit over hqdn3d to warrant that. Kill it with fire.

  REMOVE: divVerent
  REMOVE: wm4 (I don't want to keep things just because they "may" be good.)

libmpcodecs/vf_palette.c
  REMOVE: divVerent

libmpcodecs/vf_perspective.c
  We're not GIMP. And you can always do this quite easily using vf_lua...

  REMOVE: divVerent, lachs0r

  lachs0r: Files with incorrect perspective are extremely rare too. About the only real-world use for this is keystone correction, which is usually done in hardware by the projector or by graphics drivers/compositors.

libmpcodecs/vf_phase.c
  Sounds useful to properly detelecine broken input, so keep it.

  KEEP: divVerent, lachs0r
  REMOVE: wm4 (same as before, "sounds useful" != "is useful")
  REMOVE: lachs0r – Use --field-dominance.

libmpcodecs/vf_pp7.c
  A WTF filter.

  REMOVE: divVerent

libmpcodecs/vf_pp.c
  Useful for old MPEG-1 and DivX stuff.

  KEEP: divVerent

libmpcodecs/vf_pullup.c
  The one good de-teleciner.

  KEEP: divVerent

libmpcodecs/vf_qp.c
  Who would ever need this?

  REMOVE: divVerent

libmpcodecs/vf_rectangle.c
  See vf_cropdetect.

  REMOVE: divVerent

libmpcodecs/vf_remove_logo.c
  delogo is way more convenient and usually good enough.

  REMOVE: divVerent

libmpcodecs/vf_rgbtest.c
  REMOVE: divVerent

libmpcodecs/vf_rotate.c
  KEEP: divVerent

libmpcodecs/vf_sab.c
  We only need one blur. For any more there is vf_lua.

  REMOVE: divVeremt

libmpcodecs/vf_scale.c
  KEEP: divVerent

libmpcodecs/vf_screenshot.c
  Still in use for ordering purposes.

  KEEP: divVerent

libmpcodecs/vf_smartblur.c
  We only need one blur.

  REMOVE: divVerent

libmpcodecs/vf_softpulldown.c
  Is needed for proper MPEG-2 support in some cases, when encoding.

  KEEP: divVerent

libmpcodecs/vf_softskip.c
  Does nothing.

  REMOVE: divVerent

libmpcodecs/vf_spp.c
  A WTF filter.

  REMOVE: divVerent

libmpcodecs/vf_stereo3d.c
  Sometimes useful.

  KEEP: divVerent

libmpcodecs/vf_swapuv.c
  vf_lua. Nuff said.

  REMOVE: divVerent
  KEEP: wm4 (Might sometimes be useful for rawvideo. I removed vd_raw and demux_rawvideo uses ffmpeg's raw decoder now. Since we pass a libav pixel format to that decoder as input format, information about the plane order gets lost. I think.)

libmpcodecs/vf_telecine.c
  Already ported to vf_dlopen. Not needed in core. And only does evil anyway ;)

  REMOVE: divVerent

libmpcodecs/vf_test.c
  REMOVE: divVerent

libmpcodecs/vf_tfields.c
  I can see this being useful. Maybe should be moved to dlopen though.

  KEEP: divVerent
  REMOVE: wm4 (how useful?)
  REMOVE: lachs0r (not at all)

libmpcodecs/vf_tile.c
  Already ported to vf_dlopen. Not needed in core.

  REMOVE: divVerent

libmpcodecs/vf_tinterlace.c
  I can see this being useful. Maybe should be moved to dlopen though.

  KEEP: divVerent
  REMOVE: lachs0r – No. Just no. Interlacing should die in a fire.

libmpcodecs/vf_unsharp.c
  The good blur/sharpener.

  KEEP: divVerent

libmpcodecs/vf_uspp.c
  A WTF filter.

  REMOVE: divVerent

libmpcodecs/vf_yadif.c
  The good deinterlacer.

  KEEP: divVerent

libmpcodecs/vf_yuvcsp.c
  Is this needed?

  ABSTAIN: divVerent
  REMOVE: wm4 (doesn't sound terribly useful)
  REMOVE: lachs0r

libmpcodecs/vf_yvu9.c
  Already deprecated.

  REMOVE: divVerent