libaf/af_bs2b.c
  ...

libaf/af_center.c
  ...

libaf/af_channels.c
  ...

libaf/af_delay.c
  ...

libaf/af_dummy.c
  ...

libaf/af_equalizer.c
  ...

libaf/af_export.c
  ...

libaf/af_extrastereo.c
  ...

libaf/af_format.c
  ...

libaf/af_hrtf.c
  ...

libaf/af_karaoke.c
  ...

libaf/af_ladspa.c
  ...

libaf/af_lavcac3enc.c
  ...

libaf/af_lavcresample.c
  ...

libaf/af_pan.c
  ...

libaf/af_resample.c
  ...

libaf/af_resample_template.c
  ...

libaf/af_scaletempo.c
  ...

libaf/af_sinesuppress.c
  ...

libaf/af_sub.c
  ...

libaf/af_surround.c
  ...

libaf/af_sweep.c
  ...

libaf/af_tools.c
  ...

libaf/af_volnorm.c
  ...

libaf/af_volume.c
  ...

libmpcodecs/vf_1bpp.c
  ...

libmpcodecs/vf_2xsai.c
  ...

libmpcodecs/vf_ass.c
  ...

libmpcodecs/vf_blackframe.c
  ...

libmpcodecs/vf_bmovl.c
  ...

libmpcodecs/vf_boxblur.c
  ...

libmpcodecs/vf_crop.c
  ...

libmpcodecs/vf_cropdetect.c
  ...

libmpcodecs/vf_decimate.c
  ...

libmpcodecs/vf_delogo.c
  ...

libmpcodecs/vf_denoise3d.c
  ...

libmpcodecs/vf_detc.c
  ...

libmpcodecs/vf_dint.c
  ...

libmpcodecs/vf_divtc.c
  ...

libmpcodecs/vf_dlopen.c
  ...

libmpcodecs/vf_down3dright.c
  ...

libmpcodecs/vf_dsize.c
  ...

libmpcodecs/vf_dvbscale.c
  ...

libmpcodecs/vf_eq2.c
  ...

libmpcodecs/vf_eq.c
  ...

libmpcodecs/vf_expand.c
  ...

libmpcodecs/vf_field.c
  ...

libmpcodecs/vf_fil.c
  ...

libmpcodecs/vf_filmdint.c
  ...

libmpcodecs/vf_fixpts.c
  ...

libmpcodecs/vf_flip.c
  ...

libmpcodecs/vf_format.c
  ...

libmpcodecs/vf_framestep.c
  ...

libmpcodecs/vf_fspp.c
  ...

libmpcodecs/vf_geq.c
  ...

libmpcodecs/vf_gradfun.c
  ...

libmpcodecs/vf_halfpack.c
  ...

libmpcodecs/vf_harddup.c
  ...

libmpcodecs/vf_hqdn3d.c
  ...

libmpcodecs/vf_hue.c
  ...

libmpcodecs/vf_il.c
  ...

libmpcodecs/vf_ilpack.c
  ...

libmpcodecs/vf_ivtc.c
  ...

libmpcodecs/vf_kerndeint.c
  ...

libmpcodecs/vf_lavc.c
  ...

libmpcodecs/vf_lavcdeint.c
  ...

libmpcodecs/vf_mcdeint.c
  ...

libmpcodecs/vf_mirror.c
  ...

libmpcodecs/vf_noformat.c
  ...

libmpcodecs/vf_noise.c
  ...

libmpcodecs/vf_ow.c
  ...

libmpcodecs/vf_palette.c
  ...

libmpcodecs/vf_perspective.c
  ...

libmpcodecs/vf_phase.c
  ...

libmpcodecs/vf_pp7.c
  ...

libmpcodecs/vf_pp.c
  ...

libmpcodecs/vf_pullup.c
  ...

libmpcodecs/vf_qp.c
  ...

libmpcodecs/vf_rectangle.c
  ...

libmpcodecs/vf_remove_logo.c
  ...

libmpcodecs/vf_rgbtest.c
  ...

libmpcodecs/vf_rotate.c
  ...

libmpcodecs/vf_sab.c
  ...

libmpcodecs/vf_scale.c
  ...

libmpcodecs/vf_screenshot.c
  ...

libmpcodecs/vf_smartblur.c
  ...

libmpcodecs/vf_softpulldown.c
  ...

libmpcodecs/vf_softskip.c
  ...

libmpcodecs/vf_spp.c
  ...

libmpcodecs/vf_stereo3d.c
  ...

libmpcodecs/vf_swapuv.c
  ...

libmpcodecs/vf_telecine.c
  ...

libmpcodecs/vf_test.c
  ...

libmpcodecs/vf_tfields.c
  ...

libmpcodecs/vf_tile.c
  ...

libmpcodecs/vf_tinterlace.c
  ...

libmpcodecs/vf_unsharp.c
  ...

libmpcodecs/vf_uspp.c
  ...

libmpcodecs/vf_vo.c
  ...

libmpcodecs/vf_yadif.c
  ...

libmpcodecs/vf_yuvcsp.c
  ...

libmpcodecs/vf_yvu9.c
  ...
