----

If you are any of the people below, please contact us!
Send a mail to nfxjfg@googlemail.com, or post on: https://github.com/mpv-player/mpv/issues/2033

People who were contacted, but did not reply
------------------------------------------------
rguyom (some very early vd_ffmpeg.c fixes)
Stefan Huehner or Stefan Hühner (tons of code cleanups that touch everything)
Sidik Isani
Dave Lambley
Ulion (many changes all over the place)
Rich Felker
Stephen Warren
Naoya OYAMA  (ad_spdif.c)
Aaron Holtzman (sekeleton for struct vo)
Michel Lespinasse
Martin Kebert
Luca Abeni
Ville Syrjälä
Jürgen Keil (many early cleanups that touch a lot of code)
German Gomez Garcia
Uwe Reder
Pascal Haakmat
Mark Zealey
hephooey@gmail.com
Jesper Svennevid
Eric Lammerts
Dénes Balatoni
R.L. Horn
seru
Kir Kostuchenko
Baryshkov, Dmitry (lumag)
Arwed von Merkatz
Zoltan Hidvegi (hzoli)
Eviv Bulgroz
Jeremy Huddleston (maybe jeremyhu on github, for commit 9b0d8c680f634)
kiriuja
Wei Jiang
Timothy Lee
Rune Petersen
Sam Dennis
Nikolai Weibull
Loren Merritt (apart from mencoder, some small changes)
Paul Lebedev
Federico Menarini
Emanuele Giaquinta
Bryan Veal (probably "veal" in commit 116ca0c768219b10e)
Gianluigi Tiesi
Onur Küçük
Tim Wojtulewicz
Gábor Mizda
emild
Thomas Reitmayr
Chris Welton
James Warden
Sergey Malkovsky
Mathieu Schroeter
Ricardo Villalba
Benson Mitchell
Christian P. Schmidt
Francesco Lavra
Laurent
Melchior Franz
KS Ng dmbth
Endre Kollár
Yuriy Kaminskiy
Nikolay Nikolaev
Fabian Franz
nVidia Corporation
Gordon Schmidt
Bernd Ernesti
Artur Zaprzała
Vladimir Kushnir

People whose email addresses are not valid anymore
------------------------------------
Filip Kalinski (filon) <filon@pld.org.pl>
Alan Curry <pacman@world.std.com>
Bryan Chan <scorpio@acm.org> (user dead) (fakemono patch)
Aleksander V. Dyomin <fly@shax.ru> ("mail for shax.ru loops back to myself")
Evgeny Chukreev <codedj@echo.ru> ("No such user!")
Nick Kurshev <nickols_k@mail.ru> (user terminated) nickols_k@users.sourceforge.net (unknown user)
Kees Cook <mplayer@outflux.net> (user unknown)
Balazs Tibor <tibcu@sch.bme.hu> (user unknown)
Tristan <z80@oceanfree.net> (unknown user)
adland <adland123@yahoo.com> (account gone)
matthieu <mat100@ifrance.com> (probably Matthieu Castet)
Tom Lees <tal26@cam.ac.uk>
Daniel Dawson <ddawson@icehouse.net> (user does not exist)
Janusz Krzysztofik <jkrzyszt@tis.icnet.pl> (unrouteable address)
Christian <herr.mitterlehner@gsmpaaiml.com> (host not found)
